name: Generate draft release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  if_merged:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
        with:
          tag: v0.0.12
          version: v0.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
