name: Version packages

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'The type of version bump to perform.'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/setup-and-install

      - name: Print Environment Info
        run: npx lerna info
        shell: bash

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        shell: bash

      - name: Bump version of packages
        run: npx lerna version ${{ inputs.version-bump }} --yes --no-push --no-git-tag-version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Lerna version
        run: |
          LERNA_VERSION=$(jq -r '.version' lerna.json)
          echo "Using version from lerna.json: $LERNA_VERSION"
          echo "LERNA_VERSION=$LERNA_VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: releases/bump-version-${{ env.LERNA_VERSION }}
          title: releases/bump-version-${{ env.LERNA_VERSION }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          commit-message: "chore: bump version to ${{ env.LERNA_VERSION }}"
          labels: releases
          body: |
            Bump packages to ${{ env.LERNA_VERSION }}
            
            Auto-generated by [create-pull-request][1] on Version workflow
            
            [1]: https://github.com/peter-evans/create-pull-request
            
